server:
  port : 9191
  
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: PERSONNEL-SERVICE
          uri: lb://PERSONNEL-SERVICE
          predicates:
            - Path=/Personnel/**
        - id: RDV-SERVICE
          uri: lb://RDV-SERVICE
          predicates:
            - Path=/Rdv/**
        - id: PATIENT-SERVICE
          uri: lb://PATIENT-SERVICE
          predicates:
            - Path=/patient/**
        - id: m-departements
          uri: lb://m-departements
          predicates:
            - Path=/departements/**
        - id: HOSPITALISATION-SERVICE
          uri: lb://HOSPITALISATION-SERVICE
          predicates:
            - Path=/hospitalisation/**
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    

